# Generated by Django 2.1.2 on 2020-04-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200, verbose_name='名称代码')),
                ('stock_id', models.IntegerField(verbose_name='股票id')),
                ('stock_price', models.FloatField(default=0, verbose_name='价格')),
                ('stock_change', models.FloatField(default=0, verbose_name='涨跌幅')),
                ('stock_market_value', models.FloatField(default=0, verbose_name='市值')),
            ],
            options={
                'verbose_name': 'stock lists',
                'verbose_name_plural': 'stocks',
            },
        ),
    ]
