# Generated by Django 2.1.2 on 2020-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200425_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='stock_type',
            field=models.CharField(choices=[('SZ', 'sz'), ('SH', 'sh')], default='sz', max_length=200, verbose_name='类型'),
        ),
    ]
